name: docker
on:
  push:
    branches:
    - main
    tags:
    - '*'

jobs:
  image:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Gather Metadata
      id: metadata
      run: |
        if [[ "${GITHUB_REF}" =~ 'refs/tags' ]]; then \
          version="$(echo "${GITHUB_REF}" | sed -e 's|refs/tags/||')"; \
        else \
          version="latest"
        fi;
        echo "::set-output name=version::${version}"

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login
      if: ${{ github.event_name == 'push' }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Package
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: linux/arm64,linux/amd64
        target: app
        tags: bitwalker/cfdns:${{ steps.metadata.outputs.version }}
