name: release
on:
  push:
    tags:
    - '*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Gather Metadata
      id: metadata
      run: |
        version="$(echo "${GITHUB_REF}" | sed -e 's|refs/tags/||')";
        echo "::set-output name=version::${version}"
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-unknown-linux-musl
        override: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --target aarch64-unknown-linux-musl
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: |
        gh release create -R bitwalker/cfdns --target ${GITHUB_SHA} ${{ steps.metadata.outputs.version }} target/release/aarch64-unknown-linux-musl/cfdns
